---
batch_size : 8
seed : 4
# run configuration(what do you want to do?)
load_model : False                                                            # take existing trained model
diffusion_mode : False                                                        # train the diffusion model
training_mode : False                                                         # train the gradient digital twin model
activate_train_and_optimize : False                                           # train the gradient digital twin model using the active learning
find_optimal_lr : True                                                        # a setting used to find the best learning rate for the physfad optimization
optimize_model : True                                                         # run a test for all different optimisation methods and compare them
run_snr_graph : False                                                         # compare all different optimisation methods on different snr values

# Simulation Parameters
environment_file_name : "ComplexEnclosure2"
environment_noise_power : 0.01


# sizes of input output of the model
input_size : 135                                                              # number of configuration parameters
output_size : 120                                                             # number of frequencies in the channel
output_shape : [4,3]                                                          # num of transmitter, num of receivers
fres_max_range : 20   # 5                                                     # resonant frequency is between 0 and 5
chi_max_range : 30    # 100                                                   # chi values are between 0 and 100
gamma_max_range : 30  # 100                                                   # gamma values are between 0 and 100

# model parameters
hidden_size : 40
model_output_capacity : False                                                 # change if the model outputs the channel or capacity. all other functions change accordingly

# diffusion model parameters
tx_size : 6                                                                   # number of tx parameters (3 transmitters,2 values for x and y)
diffusion_sigma_inp_size : 1                                                  # another input for the sigma
# [MATH] diffusion_inp_size : input_size+tx_size+diffusion_sigma_inp_size     # set in conf class

# general training settings
max_epochs : 150
ep_log_interval : 1                                                           # every how many epochs should a message be printed
lrn_rate : 0.0005                                                             # learning rate for the training. originally divided by 10

# general optimisation settings
optim_lr : 0.002                                                              # the learning rate for the optimization step. originally 0.008
num_of_opt_iter : 3000                                                        # how many iterations in the deep learning optimization

# active training parameters
new_configuration_chance : 0.75                                               # chance to generate a new configuration and not choose one of the previous ones.
lmbda : 0.2                                                                   # strength of regularizer hyperparameter